repos:
  # Flake8 linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  # Black for Python formatting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  # Isort for import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  # Optional: remove output from Jupyter notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: v0.5.0
    hooks:
      - id: nbstripout
