task: "surface_code:rotated_memory_z"
# Valid tasks:
# - surface_code:rotated_memory_x
# - surface_code:rotated_memory_z
parameters:
  distance: 3  # Must be odd
  rounds: 2
  errors:
    after_clifford_depolarization: 0.1
    before_round_data_depolarization: 0.1
    before_measure_flip_probability: 0.1
    after_reset_flip_probability: 0.0
  sampling:
    seed: 42
    skip_ref_sample: False
    reference_sample: "auto"  # NOT IMPLEMENTED YET
    shots: 2
    console_log: True
  mapping:
    console_log: True
bitstream:
  exporting: True
  format: "zxd"
  console_log: True
exports:
  output:
    file: "output/output.json"
    prettify: True
  figure:
    exporting: True
    trans_bg: False  # Transparent background for SVG
    file: "output/CircuitFigure.svg"
  surface_code_fig:
    exporting: True
    type: "timeslice-svg"  # Valid options: "timeslice-svg", "detslice-svg"
    file: "output/SurfaceCode.svg"
  circuit:
    exporting: True
    file: "output/CircuitText.txt"
  pdf_report:
    # More PDF-related settings can be found in settings/pdf.ini
    exporting: True
    file: "examples/report_d9.pdf"
  database:
    exporting: True
    file: "db/simulations.db"
