task: "surface_code:rotated_memory_x"
# Valid tasks:
# - repetition_code:memory
# - surface_code:rotated_memory_x
# - surface_code:rotated_memory_z
# - surface_code:unrotated_memory_x
# - surface_code:unrotated_memory_z
# - color_code:memory_xyz
parameters:
  distance: 5  # distance must be odd
  rounds: 1
  errors:
    after_clifford_depolarization: 0
    before_round_data_depolarization: 0.0
    before_measure_flip_probability: 0.0
    after_reset_flip_probability: 0
  sampling:
    seed: Null
    shots: 1
    console_log: True
  mapping:
    console_log: True
exports:
  figure:
    exporting: True
    trans_bg: False
    type:
    file: "output/test_fig.svg"
  circuit:
    exporting: True
    file: "output/test_circ.txt"
  output:
    file: "output/output.json"
    prettify: True
