task: "surface_code:rotated_memory_z"
# Valid tasks:
# - surface_code:rotated_memory_x
# - surface_code:rotated_memory_z
parameters:
  distance: 3 # distance must be odd
  rounds: 1
  errors:
    after_clifford_depolarization: 0.0
    before_round_data_depolarization: 0.0
    before_measure_flip_probability: 0.0
    after_reset_flip_probability: 0.0
  sampling:
    seed: 42
    skip_ref_sample: False
    shots: 1
    console_log: True
  mapping:
    console_log: True
bitstream:
  exporting: True
  format: "zxd"
  console_log: True
exports:
  figure:
    exporting: True
    trans_bg: False
    type:
    file: "output/SVG/CircuitFigure.svg"
  circuit:
    exporting: True
    file: "output/TXT/CircuitText.txt"
  output:
    file: "output/JSON/output.json"
    prettify: True
  pdf_report:
  # More PDF related settings can be found in settings/pdf.ini
    exporting: True
    file: "output/PDF/report_d9.pdf"
  database:
    exporting: True
    file: "db/simulations.db"