task: "surface_code:rotated_memory_z"
# Valid tasks include:
# - repetition_code:memory
# - surface_code:rotated_memory_x
# - surface_code:rotated_memory_z
# - surface_code:unrotated_memory_x
# - surface_code:unrotated_memory_z
# - color_code:memory_xyz
parameters:
  distance: 5
  # distance must be odd
  rounds: 5
  errors:
    after_clifford_depolarization: 0.0
    before_round_data_depolarization: 0.1
    before_measure_flip_probability: 0.1
    after_reset_flip_probability: 0.0
  sampling:
    shots: 100
    console_log: True
exports:
  figure:
    exporting: True
    trans_bg: False
    file: "output/test_fig.svg"
  circuit:
    exporting: True
    file: "output/test_circ.txt"
  output:
    file: "output/output.json"
    prettify: True
